<?php $_links = $this->getLinks(); ?>
<script type="text/javascript">
var URL = '<?php echo $this->getUrl(); ?>';
</script>
<?php if(count($_links)>0): ?>
<div class="hdMeta">
<ul class="hdMetaLinks"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
    <li><!--- Start CMS header_cs_number-->
		<style>
			.thm-spinbasket #header {
				height: 120px;
			}
			.hdMeta {
				height: 18px;
			}
		</style>
		<span class="hdMetaLink">HOTLINE: HCM (08) 3942 xxx - HN (04) 7300 xxx</span>
		<!--- End CMS header_cs_number-->
		<span class="hdSeperator">|</span>
	</li>
	<li>
		<a class="hdMetaLink login-overlay-active" href="/index.php/wishlist/" title="Danh sách mong muốn">Danh sách mong muốn</a><span class="hdSeperator">|</span>
	</li>
    <?php foreach($_links as $_link): ?>
	    <?php if($_link->getLabel() == 'Log Out'): ?>
        <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> 
        	class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?>
        		<?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?>
        			<a class="hdMetaLink" href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>>
        				<?php echo $this->__('Đăng xuất') ?>
        			</a><?php echo $_link->getAfterText() ?></li>
		<span class="hdSeperator">|</span></li>
		<?php endif; ?>
    <?php endforeach; ?>
	 <?php if(!$this->helper('customer')->isLoggedIn()) :?>
	
	 <li><a class="top-link-last" title="<?php echo $this->__('Đăng nhập / Đăng ký') ?>" id="alogin" href="javascript:void(0)" ><?php echo $this->__('Đăng nhập / Đăng ký') ?></a></li>
	 <?php endif; ?>
</ul>
</div>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('quicklogin/tinybox.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('quicklogin/quicklogin.js') ?>"></script>



